export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGN_IN_SUCCESS = 'AUTH_SIGN_IN_SUCCESS';
export const AUTH_SIGN_IN_FAILURE = 'AUTH_SIGN_IN_FAILURE';

export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';
export const AUTH_SIGN_OUT_SUCCESS = 'AUTH_SIGN_OUT_SUCCESS';
export const AUTH_SIGN_OUT_FAILURE = 'AUTH_SIGN_OUT_FAILURE';

export const USERS_GET = 'USERS_GET';
export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS';
export const USERS_GET_FAILURE = 'USERS_GET_FAILURE';

export const USERS_POST = 'USERS_POST';
export const USERS_POST_SUCCESS = 'USERS_POST_SUCCESS';
export const USERS_POST_FAILURE = 'USERS_POST_FAILURE';

export const USERS_EDIT = 'USERS_EDIT';
export const USERS_EDIT_SUCCESS = 'USERS_EDIT_SUCCESS';
export const USERS_EDIT_FAILURE = 'USERS_EDIT_FAILURE';

export const USERS_DELETE_MANY = 'USERS_DELETE_MANY';
export const USERS_DELETE_MANY_SUCCESS = 'USERS_DELETE_MANY_SUCCESS';
export const USERS_DELETE_MANY_FAILURE = 'USERS_DELETE_MANY_FAILURE';

export const USERS_SET_SELECTED_IDS = 'USERS_SET_SELECTED_IDS';
export const USERS_SET_LIMIT = 'USERS_SET_LIMIT';
export const USERS_SET_PAGE = 'USERS_SET_PAGE';

export const TOAST_ADD = 'TOAST_ADD';
export const TOAST_REMOVE = 'TOAST_REMOVE';
